<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-12T15:36:07+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      enable_legacy_src_namespace
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'enable_legacy_src_namespace' => false,
    'enable_legacy_namespace' => false,
);
