<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-11-04T21:38:22+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      enable_legacy_src_namespace
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'enable_legacy_src_namespace' => false,
);
