<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-10-05T14:33:00-07:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'misc' => array(
        'do_page_reindex_check' => true,
        'access_entity_updated' => 1475703177,
    ),
);
