<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-11-08T19:25:41+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'misc' => array(
        'do_page_reindex_check' => true,
        'access_entity_updated' => 1478633141,
    ),
);
