<?php

namespace DoctrineProxies\__CG__\Concrete\Core\StyleCustomizer\Inline;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StyleSet extends \Concrete\Core\StyleCustomizer\Inline\StyleSet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'issID', 'customClass', 'backgroundColor', 'backgroundImageFileID', 'backgroundRepeat', 'borderColor', 'borderStyle', 'borderWidth', 'borderRadius', 'baseFontSize', 'alignment', 'textColor', 'linkColor', 'marginTop', 'marginBottom', 'marginLeft', 'marginRight', 'paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight', 'rotate', 'boxShadowHorizontal', 'boxShadowVertical', 'boxShadowBlur', 'boxShadowSpread', 'boxShadowColor');
        }

        return array('__isInitialized__', 'issID', 'customClass', 'backgroundColor', 'backgroundImageFileID', 'backgroundRepeat', 'borderColor', 'borderStyle', 'borderWidth', 'borderRadius', 'baseFontSize', 'alignment', 'textColor', 'linkColor', 'marginTop', 'marginBottom', 'marginLeft', 'marginRight', 'paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight', 'rotate', 'boxShadowHorizontal', 'boxShadowVertical', 'boxShadowBlur', 'boxShadowSpread', 'boxShadowColor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StyleSet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCustomClass($customClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomClass', array($customClass));

        return parent::setCustomClass($customClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomClass', array());

        return parent::getCustomClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderWidth($borderWidth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderWidth', array($borderWidth));

        return parent::setBorderWidth($borderWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderWidth', array());

        return parent::getBorderWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlignment($alignment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlignment', array($alignment));

        return parent::setAlignment($alignment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlignment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlignment', array());

        return parent::getAlignment();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundRepeat($backgroundRepeat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundRepeat', array($backgroundRepeat));

        return parent::setBackgroundRepeat($backgroundRepeat);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundRepeat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundRepeat', array());

        return parent::getBackgroundRepeat();
    }

    /**
     * {@inheritDoc}
     */
    public function setBaseFontSize($baseFontSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBaseFontSize', array($baseFontSize));

        return parent::setBaseFontSize($baseFontSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaseFontSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaseFontSize', array());

        return parent::getBaseFontSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderColor($borderColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderColor', array($borderColor));

        return parent::setBorderColor($borderColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderColor', array());

        return parent::getBorderColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderStyle($borderStyle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderStyle', array($borderStyle));

        return parent::setBorderStyle($borderStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderStyle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderStyle', array());

        return parent::getBorderStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setBorderRadius($borderRadius)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBorderRadius', array($borderRadius));

        return parent::setBorderRadius($borderRadius);
    }

    /**
     * {@inheritDoc}
     */
    public function getBorderRadius()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBorderRadius', array());

        return parent::getBorderRadius();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxShadowBlur($boxShadowBlur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxShadowBlur', array($boxShadowBlur));

        return parent::setBoxShadowBlur($boxShadowBlur);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxShadowBlur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxShadowBlur', array());

        return parent::getBoxShadowBlur();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxShadowColor($boxShadowColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxShadowColor', array($boxShadowColor));

        return parent::setBoxShadowColor($boxShadowColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxShadowColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxShadowColor', array());

        return parent::getBoxShadowColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxShadowHorizontal($boxShadowHorizontal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxShadowHorizontal', array($boxShadowHorizontal));

        return parent::setBoxShadowHorizontal($boxShadowHorizontal);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxShadowHorizontal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxShadowHorizontal', array());

        return parent::getBoxShadowHorizontal();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxShadowSpread($boxShadowSpread)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxShadowSpread', array($boxShadowSpread));

        return parent::setBoxShadowSpread($boxShadowSpread);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxShadowSpread()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxShadowSpread', array());

        return parent::getBoxShadowSpread();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoxShadowVertical($boxShadowVertical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoxShadowVertical', array($boxShadowVertical));

        return parent::setBoxShadowVertical($boxShadowVertical);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxShadowVertical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxShadowVertical', array());

        return parent::getBoxShadowVertical();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkColor($linkColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkColor', array($linkColor));

        return parent::setLinkColor($linkColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkColor', array());

        return parent::getLinkColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setTextColor($textColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTextColor', array($textColor));

        return parent::setTextColor($textColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getTextColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTextColor', array());

        return parent::getTextColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRotate($rotate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRotate', array($rotate));

        return parent::setRotate($rotate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRotate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRotate', array());

        return parent::getRotate();
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', array());

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarginBottom($marginBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarginBottom', array($marginBottom));

        return parent::setMarginBottom($marginBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarginBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarginBottom', array());

        return parent::getMarginBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarginLeft($marginLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarginLeft', array($marginLeft));

        return parent::setMarginLeft($marginLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarginLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarginLeft', array());

        return parent::getMarginLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarginRight($marginRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarginRight', array($marginRight));

        return parent::setMarginRight($marginRight);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarginRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarginRight', array());

        return parent::getMarginRight();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarginTop($marginTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarginTop', array($marginTop));

        return parent::setMarginTop($marginTop);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarginTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarginTop', array());

        return parent::getMarginTop();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaddingBottom($paddingBottom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaddingBottom', array($paddingBottom));

        return parent::setPaddingBottom($paddingBottom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaddingBottom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaddingBottom', array());

        return parent::getPaddingBottom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaddingLeft($paddingLeft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaddingLeft', array($paddingLeft));

        return parent::setPaddingLeft($paddingLeft);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaddingLeft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaddingLeft', array());

        return parent::getPaddingLeft();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaddingRight($paddingRight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaddingRight', array($paddingRight));

        return parent::setPaddingRight($paddingRight);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaddingRight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaddingRight', array());

        return parent::getPaddingRight();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaddingTop($paddingTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaddingTop', array($paddingTop));

        return parent::setPaddingTop($paddingTop);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaddingTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaddingTop', array());

        return parent::getPaddingTop();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundColor($backgroundColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundColor', array($backgroundColor));

        return parent::setBackgroundColor($backgroundColor);
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundImageFileID($backgroundImageFileID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundImageFileID', array($backgroundImageFileID));

        return parent::setBackgroundImageFileID($backgroundImageFileID);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundColor', array());

        return parent::getBackgroundColor();
    }

    /**
     * {@inheritDoc}
     */
    public function getBackgroundImageFileObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackgroundImageFileObject', array());

        return parent::getBackgroundImageFileObject();
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', array());

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function import(\SimpleXMLElement $node)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'import', array($node));

        return parent::import($node);
    }

    /**
     * {@inheritDoc}
     */
    public function export(\SimpleXMLElement $node)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'export', array($node));

        return parent::export($node);
    }

}
