<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Page;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PagePath extends \Concrete\Core\Page\PagePath implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'cPath', 'ppID', 'cID', 'ppIsCanonical');
        }

        return array('__isInitialized__', 'cPath', 'ppID', 'cID', 'ppIsCanonical');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PagePath $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPagePathID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagePathID', array());

        return parent::getPagePathID();
    }

    /**
     * {@inheritDoc}
     */
    public function getPagePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagePath', array());

        return parent::getPagePath();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagePath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagePath', array($path));

        return parent::setPagePath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function setPageObject(\Concrete\Core\Page\Page $c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageObject', array($c));

        return parent::setPageObject($c);
    }

    /**
     * {@inheritDoc}
     */
    public function setPagePathIsCanonical($ppIsCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagePathIsCanonical', array($ppIsCanonical));

        return parent::setPagePathIsCanonical($ppIsCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function isPagePathCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPagePathCanonical', array());

        return parent::isPagePathCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollectionID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollectionID', array());

        return parent::getCollectionID();
    }

}
