image:
  file: .gitpod/Dockerfile
  context: .gitpod
ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - name: Terminal
    command: >
      echo "";
      echo "Commands you can try:";
      echo " * nginx";
      echo " * nginx -s stop";
      echo " * nginx -s reload";
      echo " * gp open /etc/nginx/nginx.conf";
      echo " * gp open /var/log/nginx/access.log";
      echo " * gp open /var/log/nginx/error.log";
  - name: Nginx
    command: >
      nginx &&
      multitail /var/log/nginx/access.log -I /var/log/nginx/error.log