<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:31.
 */
class ConcreteUpgradeVersion550HelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteUpgradeVersion550Helper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConcreteUpgradeVersion550Helper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ConcreteUpgradeVersion550Helper::run
     * @todo   Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUpgradeVersion550Helper::installSinglePages
     * @todo   Implement testInstallSinglePages().
     */
    public function testInstallSinglePages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUpgradeVersion550Helper::migrateOldDashboard
     * @todo   Implement testMigrateOldDashboard().
     */
    public function testMigrateOldDashboard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUpgradeVersion550Helper::installBlockTypes
     * @todo   Implement testInstallBlockTypes().
     */
    public function testInstallBlockTypes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUpgradeVersion550Helper::installDashboard
     * @todo   Implement testInstallDashboard().
     */
    public function testInstallDashboard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUpgradeVersion550Helper::prepare
     * @todo   Implement testPrepare().
     */
    public function testPrepare() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
