<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Block\BlockType;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BlockType extends \Concrete\Core\Block\BlockType\BlockType implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'controller', 'btIgnorePageThemeGridFrameworkContainer', 'btID', 'btHandle', 'btName', 'btDescription', 'btCopyWhenPropagate', 'btIncludeAll', 'btIsInternal', 'btSupportsInlineEdit', 'btSupportsInlineAdd', 'btInterfaceHeight', 'btInterfaceWidth', 'pkgID');
        }

        return array('__isInitialized__', 'controller', 'btIgnorePageThemeGridFrameworkContainer', 'btID', 'btHandle', 'btName', 'btDescription', 'btCopyWhenPropagate', 'btIncludeAll', 'btIsInternal', 'btSupportsInlineEdit', 'btSupportsInlineAdd', 'btInterfaceHeight', 'btInterfaceWidth', 'pkgID');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BlockType $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setBlockTypeName($btName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlockTypeName', array($btName));

        return parent::setBlockTypeName($btName);
    }

    /**
     * {@inheritDoc}
     */
    public function setBlockTypeDescription($btDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlockTypeDescription', array($btDescription));

        return parent::setBlockTypeDescription($btDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function setBlockTypeHandle($btHandle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlockTypeHandle', array($btHandle));

        return parent::setBlockTypeHandle($btHandle);
    }

    /**
     * {@inheritDoc}
     */
    public function hasAddTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasAddTemplate', array());

        return parent::hasAddTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeComposerTemplates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeComposerTemplates', array());

        return parent::getBlockTypeComposerTemplates();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeHandle', array());

        return parent::getBlockTypeHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function supportsInlineEdit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'supportsInlineEdit', array());

        return parent::supportsInlineEdit();
    }

    /**
     * {@inheritDoc}
     */
    public function supportsInlineAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'supportsInlineAdd', array());

        return parent::supportsInlineAdd();
    }

    /**
     * {@inheritDoc}
     */
    public function isInternalBlockType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInternalBlockType', array());

        return parent::isInternalBlockType();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeInterfaceWidth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeInterfaceWidth', array());

        return parent::getBlockTypeInterfaceWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeInterfaceHeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeInterfaceHeight', array());

        return parent::getBlockTypeInterfaceHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function ignorePageThemeGridFrameworkContainer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ignorePageThemeGridFrameworkContainer', array());

        return parent::ignorePageThemeGridFrameworkContainer();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageID', array());

        return parent::getPackageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeDescription', array());

        return parent::getBlockTypeDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeName', array());

        return parent::getBlockTypeName();
    }

    /**
     * {@inheritDoc}
     */
    public function isCopiedWhenPropagated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCopiedWhenPropagated', array());

        return parent::isCopiedWhenPropagated();
    }

    /**
     * {@inheritDoc}
     */
    public function includeAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'includeAll', array());

        return parent::includeAll();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeClassFromHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeClassFromHandle', array());

        return parent::getBlockTypeClassFromHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeClass', array());

        return parent::getBlockTypeClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageHandle', array());

        return parent::getPackageHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeSets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeSets', array());

        return parent::getBlockTypeSets();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeID', array());

        return parent::getBlockTypeID();
    }

    /**
     * {@inheritDoc}
     */
    public function getCount($ignoreUnapprovedVersions = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCount', array($ignoreUnapprovedVersions));

        return parent::getCount($ignoreUnapprovedVersions);
    }

    /**
     * {@inheritDoc}
     */
    public function canUnInstall()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canUnInstall', array());

        return parent::canUnInstall();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlockTypeInternal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlockTypeInternal', array());

        return parent::isBlockTypeInternal();
    }

    /**
     * {@inheritDoc}
     */
    public function render($view = 'view')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'render', array($view));

        return parent::render($view);
    }

    /**
     * {@inheritDoc}
     */
    public function getController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getController', array());

        return parent::getController();
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockTypeCustomTemplates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockTypeCustomTemplates', array());

        return parent::getBlockTypeCustomTemplates();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlockTypeDisplayOrder($displayOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlockTypeDisplayOrder', array($displayOrder));

        return parent::setBlockTypeDisplayOrder($displayOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function refresh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'refresh', array());

        return parent::refresh();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function add($data, $c = false, $a = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'add', array($data, $c, $a));

        return parent::add($data, $c, $a);
    }

}
