<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Page;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Feed extends \Concrete\Core\Page\Feed implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'itemsPerFeed', 'checkPagePermissions', 'pfDescription', 'pfHandle', 'pfTitle', 'pfID', 'cParentID', 'ptID', 'pfIncludeAllDescendents', 'pfDisplayAliases', 'pfContentToDisplay', 'pfAreaHandleToDisplay', 'pfDisplayFeaturedOnly');
        }

        return array('__isInitialized__', 'itemsPerFeed', 'checkPagePermissions', 'pfDescription', 'pfHandle', 'pfTitle', 'pfID', 'cParentID', 'ptID', 'pfIncludeAllDescendents', 'pfDisplayAliases', 'pfContentToDisplay', 'pfAreaHandleToDisplay', 'pfDisplayFeaturedOnly');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Feed $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setParentID($cParentID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentID', array($cParentID));

        return parent::setParentID($cParentID);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentID', array());

        return parent::getParentID();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($pfDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($pfDescription));

        return parent::setDescription($pfDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayAliases($pfDisplayAliases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayAliases', array($pfDisplayAliases));

        return parent::setDisplayAliases($pfDisplayAliases);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayAliases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayAliases', array());

        return parent::getDisplayAliases();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayFeaturedOnly($pfDisplayFeaturedOnly)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayFeaturedOnly', array($pfDisplayFeaturedOnly));

        return parent::setDisplayFeaturedOnly($pfDisplayFeaturedOnly);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayFeaturedOnly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayFeaturedOnly', array());

        return parent::getDisplayFeaturedOnly();
    }

    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', array());

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function setIncludeAllDescendents($pfIncludeAllDescendents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIncludeAllDescendents', array($pfIncludeAllDescendents));

        return parent::setIncludeAllDescendents($pfIncludeAllDescendents);
    }

    /**
     * {@inheritDoc}
     */
    public function getIncludeAllDescendents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIncludeAllDescendents', array());

        return parent::getIncludeAllDescendents();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($pfTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($pfTitle));

        return parent::setTitle($pfTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageTypeID($ptID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageTypeID', array($ptID));

        return parent::setPageTypeID($ptID);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageTypeID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageTypeID', array());

        return parent::getPageTypeID();
    }

    /**
     * {@inheritDoc}
     */
    public function setHandle($pfHandle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHandle', array($pfHandle));

        return parent::setHandle($pfHandle);
    }

    /**
     * {@inheritDoc}
     */
    public function getHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHandle', array());

        return parent::getHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function displayShortDescriptionContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'displayShortDescriptionContent', array());

        return parent::displayShortDescriptionContent();
    }

    /**
     * {@inheritDoc}
     */
    public function displayAreaContent($arHandle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'displayAreaContent', array($arHandle));

        return parent::displayAreaContent($arHandle);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeOfContentToDisplay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeOfContentToDisplay', array());

        return parent::getTypeOfContentToDisplay();
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaHandleToDisplay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaHandleToDisplay', array());

        return parent::getAreaHandleToDisplay();
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedURL', array());

        return parent::getFeedURL();
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', array());

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

    /**
     * {@inheritDoc}
     */
    public function ignorePermissions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ignorePermissions', array());

        return parent::ignorePermissions();
    }

    /**
     * {@inheritDoc}
     */
    public function getPageListObject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageListObject', array());

        return parent::getPageListObject();
    }

    /**
     * {@inheritDoc}
     */
    public function getOutput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutput', array());

        return parent::getOutput();
    }

}
