<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:27.
 */
class ConcreteDashboardDefaultMenuTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteDashboardDefaultMenu
     */
	 protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/dashboard');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
	 public function testClasses() {
		 $this->assertTrue($this->object instanceof ConcreteDashboardHelper);
		 $this->assertTrue(class_exists('ConcreteDashboardMenu'));
		 $this->assertTrue(class_exists('ConcreteDashboardDefaultMenu'));
	 }


}
