<?
defined('C5_EXECUTE') or die("Access Denied.");
$list = \Concrete\Core\Foundation\ClassAliasList::getInstance();
$list->registerMultiple(array(
	'Cache' => 'Core\Cache\Cache',
	'CacheLocal' => 'Core\Cache\CacheLocal',
	'Database' => 'Core\Database\Database',
	'Environment' => 'Core\Foundation\Environment',
	'Localization' => 'Core\Localization\Localization',
	'Redirect' => 'Core\Routing\Redirect',
	'RedirectResponse' => 'Core\Routing\RedirectResponse',
	'Request' => 'Core\Http\Request',
	'Response' => 'Core\Http\Response',
	'Cookie' => 'Core\Cookie\Cookie',
	'Events' => 'Core\Events\Events',
	'Page' => 'Core\Page\Page',
	'SinglePage' => 'Core\Page\Single',
	'Config' => 'Core\Config\Config',
	'PageType' => 'Core\Page\Type\Type',
	'PageTheme' => 'Core\Page\Theme\Theme',
	'PageList' => 'Core\Page\List',
	'Block' => 'Core\Page\Block',
	'BlockType' => 'Core\Block\BlockType\BlockType',
	'Conversation' => 'Core\Conversation\Conversation',
	'Package' => 'Core\Package\Package',
	'Collection' => 'Core\Page\Collection\Collection',
	'Area' => 'Core\Area\Area',
	'Stack' => 'Core\Page\Stack\Stack',
	'View' => 'Core\View\View',
	'Job' => 'Core\Job\Job',
	'JobSet' => 'Core\Job\Set',
	'File' => 'Core\File\File',
	'FileSet' => 'Core\FileSet\FileSet',
	'Group' => 'Core\User\Group\Group',
	'FileList' => 'Core\File\List',
	'QueueableJob' => 'Core\Job\QueueableJob',
	'Permissions' => 'Core\Permission\Checker',
	'Stack' => 'Core\Page\Stack\Stack',
	'User' => 'Core\User\User',
	'UserInfo' => 'Core\User\UserInfo',
	'Log' => 'Core\Log\Log',
	'StartingPointPackage' => 'Core\Package\StartingPointPackage',
	'AuthenticationType' => 'Core\Authentication\AuthenticationType',
	'ConcreteAuthenticationTypeController' => 'Core\Authentication\Type\Concrete',
	'FacebookAuthenticationTypeController' => 'Core\Authentication\Type\Facebook',
	'GroupTree' => 'Core\Tree\Type\Group',
	'GroupTreeNode' => 'Core\Tree\Node\Type\Group'

));