<?php

declare(strict_types=1);

namespace Concrete\Core\Support\Symbol;

use Concrete\Core\Permission\Checker;
use Concrete\Core\Support\Symbol\CheckerGenerator\Method;
use Concrete\Core\Support\Symbol\ClassSymbol\ClassSymbol;

defined('C5_EXECUTE') or die('Access Denied.');

/**
 * Generate a stub file for PHPStan, describing (with @method annotations) the methods that are handled with __call/__callStatic:
 * - the facades
 * - the Permission\Checker class
 */
final class PHPStanStubGenerator
{
    /**
     * @var \Concrete\Core\Support\Symbol\SymbolGenerator
     */
    private $symbolGenerator;

    /**
     * @var \Concrete\Core\Support\Symbol\PhpDocTypeResolver
     */
    private $typeResolver;

    /**
     * The classes declared in other stub files (array keys are the lower-case fully-qualified class names).
     *
     * @var array<string, true>
     */
    private $classesInOtherStubs = [];

    public function __construct(SymbolGenerator $symbolGenerator, PhpDocTypeResolver $typeResolver)
    {
        $this->symbolGenerator = $symbolGenerator;
        $this->typeResolver = $typeResolver;
    }

    /**
     * Add other stub files (or directories containing them) that PHPStan will load: the classes they declare won't be declared in the generated file.
     *
     * @return $this
     */
    public function addOtherStubFiles(string ...$paths): self
    {
        foreach ($paths as $path) {
            if (is_dir($path)) {
                $files = [];
                foreach (new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path, \FilesystemIterator::SKIP_DOTS)) as $file) {
                    if (preg_match('/\.(stub|php)$/i', $file->getFilename())) {
                        $files[] = $file->getPathname();
                    }
                }
            } elseif (is_file($path)) {
                $files = [$path];
            } else {
                throw new \RuntimeException("Unable to find the stub file/directory {$path}");
            }
            foreach ($files as $file) {
                foreach ($this->listDeclaredClasses($file) as $fqn) {
                    $this->classesInOtherStubs[strtolower($fqn)] = true;
                }
            }
        }

        return $this;
    }

    public function render(string $eol = "\n", string $padding = '    '): string
    {
        $classes = [];
        foreach ($this->symbolGenerator->getFacades() as $facade) {
            $classes[$facade->getFacadeReflectionClass()->getName()] = $this->renderFacadeLines($facade, $padding);
        }
        $classes[Checker::class] = $this->renderCheckerLines($padding);
        $classes += $this->renderReferencedClassesLines($classes, $padding);
        $namespaces = [];
        foreach ($classes as $fqn => $classLines) {
            $p = strrpos($fqn, '\\');
            $namespace = $p === false ? '' : substr($fqn, 0, $p);
            $namespaces[$namespace][$fqn] = $classLines;
        }
        ksort($namespaces, SORT_STRING);
        $lines = [
            '<?php',
            '',
            '// Generated by the c5:ide-symbols CLI command on ' . date('c'),
            '// This is a stub file for PHPStan: it describes the methods handled by __call/__callStatic with @method annotations.',
        ];
        foreach ($namespaces as $namespace => $namespaceClasses) {
            ksort($namespaceClasses, SORT_STRING);
            $lines[] = '';
            $lines[] = rtrim("namespace {$namespace}");
            $lines[] = '{';
            $first = true;
            foreach ($namespaceClasses as $classLines) {
                if ($first) {
                    $first = false;
                } else {
                    $lines[] = '';
                }
                foreach ($classLines as $line) {
                    $lines[] = rtrim("{$padding}{$line}");
                }
            }
            $lines[] = '}';
        }
        $lines[] = '';

        return implode($eol, $lines);
    }

    /**
     * @return string[]
     */
    private function renderFacadeLines(ClassSymbol $facade, string $padding): array
    {
        $facadeClass = $facade->getFacadeReflectionClass();
        $rootClass = $facade->getReflectionClass();
        $annotations = [];
        foreach ($rootClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
            $name = $method->getName();
            if (strpos($name, '__') === 0 || isset($annotations[$name]) || $facadeClass->hasMethod($name)) {
                continue;
            }
            $annotations[$name] = '@method static ' . $this->renderMethodSignature($method);
        }
        ksort($annotations, SORT_NATURAL | SORT_FLAG_CASE);

        return $this->renderClassLines(
            $facadeClass,
            "Facade forwarding the static calls to an instance of \\{$rootClass->getName()}",
            $annotations,
            $padding
        );
    }

    /**
     * @return string[]
     */
    private function renderCheckerLines(string $padding): array
    {
        $annotations = [];
        foreach ($this->symbolGenerator->getCheckerGenerator()->getMethods() as $method) {
            $annotations[] = '@method ' . $this->renderCheckerMethodSignature($method);
        }

        return $this->renderClassLines(
            new \ReflectionClass(Checker::class),
            'The methods correspond to the permission keys and to the methods of the permission response classes',
            $annotations,
            $padding
        );
    }

    /**
     * @param string[] $annotations
     *
     * @return string[]
     */
    private function renderClassLines(\ReflectionClass $class, string $description, array $annotations, string $padding): array
    {
        $lines = [
            '/**',
            " * {$description}.",
        ];
        if ($annotations !== []) {
            $lines[] = ' *';
            foreach ($annotations as $annotation) {
                $lines[] = " * {$annotation}";
            }
        }
        $lines[] = ' */';
        if ($class->isInterface()) {
            $kind = 'interface';
        } elseif ($class->isTrait()) {
            $kind = 'trait';
        } else {
            $kind = 'class';
        }
        $lines[] = "{$kind} {$class->getShortName()}";
        $lines[] = '{';
        $lines[] = '}';

        return $lines;
    }

    /**
     * PHPStan validates the stub files in isolation: the classes referenced in the annotations must be declared in the stub file too.
     *
     * @param array<string, string[]> $classes array keys are the fully-qualified class names, array values are the lines already rendered
     *
     * @return array<string, string[]> array keys are the fully-qualified class names, array values are the lines
     */
    private function renderReferencedClassesLines(array $classes, string $padding): array
    {
        $result = [];
        $matches = null;
        $pending = $classes;
        while ($pending !== []) {
            $added = [];
            foreach ($pending as $classLines) {
                foreach ($classLines as $line) {
                    if (!preg_match_all('/\\\\([A-Za-z_][A-Za-z0-9_\\\\]*)/', $line, $matches)) {
                        continue;
                    }
                    foreach ($matches[1] as $fqn) {
                        if (isset($classes[$fqn]) || isset($result[$fqn])) {
                            continue;
                        }
                        try {
                            $class = new \ReflectionClass($fqn);
                        } catch (\Throwable $_) {
                            continue;
                        }
                        if ($class->isInternal() || isset($classes[$class->getName()]) || isset($result[$class->getName()]) || isset($this->classesInOtherStubs[strtolower($class->getName())])) {
                            continue;
                        }
                        $result[$class->getName()] = $added[$class->getName()] = $this->renderClassLines(
                            $class,
                            'Empty declaration: it exists because PHPStan validates the stub files in isolation',
                            $this->getClassAnnotations($class),
                            $padding
                        );
                    }
                }
            }
            $pending = $added;
        }

        return $result;
    }

    /**
     * Get the class-level PHPDoc annotations that PHPStan should know (PHPStan ignores the actual PHPDoc block of the classes declared in stub files).
     * Only the annotations that make sense in an empty class declaration are considered (for example, @extends/@implements/@template are not).
     *
     * @return string[] the annotations, with the class names resolved to fully-qualified ones
     */
    private function getClassAnnotations(\ReflectionClass $class): array
    {
        $docComment = $class->getDocComment();
        if ($docComment === false) {
            return [];
        }
        $result = [];
        $matches = null;
        foreach (preg_split('/\r\n|\n|\r/', $docComment) as $line) {
            if (!preg_match('/^\s*\*?\s*(@(?:mixin|method|property|property-read|property-write)\s+)(.+?)\s*$/', $line, $matches)) {
                continue;
            }
            $result[] = $matches[1] . preg_replace_callback(
                '/\$?\\\\?[A-Za-z_][A-Za-z0-9_\\\\]*/',
                function (array $match) use ($class): string {
                    if ($match[0][0] === '$') {
                        return $match[0];
                    }
                    $resolved = $this->typeResolver->resolvePhpDocType($match[0], $class);

                    return $resolved === '' ? $match[0] : $resolved;
                },
                $matches[2]
            );
        }

        return $result;
    }

    /**
     * List the classes/interfaces/traits declared in a PHP file.
     *
     * @return string[] the fully-qualified class names
     */
    private function listDeclaredClasses(string $file): array
    {
        $result = [];
        $namespace = '';
        $tokens = token_get_all((string) file_get_contents($file));
        $count = count($tokens);
        $nameTokens = [T_STRING, T_NS_SEPARATOR];
        if (defined('T_NAME_QUALIFIED')) {
            $nameTokens[] = T_NAME_QUALIFIED;
        }
        for ($i = 0; $i < $count; $i++) {
            $token = $tokens[$i];
            if (!is_array($token)) {
                continue;
            }
            switch ($token[0]) {
                case T_NAMESPACE:
                    $namespace = '';
                    for ($j = $i + 1; $j < $count && is_array($tokens[$j]); $j++) {
                        if (in_array($tokens[$j][0], $nameTokens, true)) {
                            $namespace .= $tokens[$j][1];
                        } elseif ($tokens[$j][0] !== T_WHITESPACE && $tokens[$j][0] !== T_COMMENT) {
                            break;
                        }
                    }
                    break;
                case T_CLASS:
                case T_INTERFACE:
                case T_TRAIT:
                    if ($i > 0 && is_array($tokens[$i - 1]) && $tokens[$i - 1][0] === T_DOUBLE_COLON) {
                        // Foo::class
                        break;
                    }
                    for ($j = $i + 1; $j < $count && is_array($tokens[$j]); $j++) {
                        if ($tokens[$j][0] === T_STRING) {
                            $result[] = ltrim($namespace . '\\' . $tokens[$j][1], '\\');
                            break;
                        }
                        if ($tokens[$j][0] !== T_WHITESPACE && $tokens[$j][0] !== T_COMMENT) {
                            break;
                        }
                    }
                    break;
            }
        }

        return $result;
    }

    private function renderMethodSignature(\ReflectionMethod $method): string
    {
        $returnType = $this->typeResolver->resolveReturnType($method);
        if ($returnType === '') {
            $returnType = 'mixed';
        }
        $parameters = [];
        foreach ($method->getParameters() as $parameter) {
            $parameters[] = $this->renderParameter($parameter);
        }

        return "{$returnType} {$method->getName()}(" . implode(', ', $parameters) . ')';
    }

    private function renderParameter(\ReflectionParameter $parameter): string
    {
        $result = $this->typeResolver->resolveParameterType($parameter);
        if ($result !== '') {
            $result .= ' ';
        }
        if ($parameter->isPassedByReference()) {
            $result .= '&';
        }
        if ($parameter->isVariadic()) {
            $result .= '...';
        }
        $result .= '$' . $parameter->getName();
        if ($parameter->isDefaultValueAvailable()) {
            $result .= ' = ' . $this->renderDefaultValue($parameter);
        }

        return $result;
    }

    private function renderDefaultValue(\ReflectionParameter $parameter): string
    {
        try {
            // We use the actual values also for constants, so that the stub file doesn't depend on them
            $value = $parameter->getDefaultValue();
        } catch (\Throwable $_) {
            return 'null';
        }
        if (is_array($value)) {
            return $value === [] ? '[]' : str_replace(["\r", "\n"], '', var_export($value, true));
        }
        if ($value === null) {
            return 'null';
        }
        if (is_scalar($value)) {
            return var_export($value, true);
        }

        return 'null';
    }

    private function renderCheckerMethodSignature(Method $method): string
    {
        // Prefix the class names with a backslash, since the arguments are rendered without the leading backslash
        $arguments = preg_replace('/(^|,\s*)([A-Z][A-Za-z0-9_\\\\]*)(\s)/', '$1\\\\$2$3', $method->getArguments());
        if ($arguments === '' && $method->getSees() === []) {
            // Methods corresponding to permission keys: the arguments are forwarded to the permission key validation
            $arguments = 'mixed ...$args';
        }
        $returnType = $method->getReturnType();
        if ($returnType === '') {
            $returnType = 'mixed';
        }

        return "{$returnType} {$method->getName()}({$arguments})";
    }
}
