<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:30.
 */
class ConcreteInterfaceHelpHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteInterfaceHelpHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/interface/help');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	 public function testObjectClass() {
		 $this->assertTrue($this->object instanceof ConcreteInterfaceHelpHelper);
	 }

    /**
     * @covers ConcreteInterfaceHelpHelper::getBlockTypes
     * @todo   Implement testGetBlockTypes().
     */
    public function testGetBlockTypes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelpHelper::getPages
     * @todo   Implement testGetPages().
     */
    public function testGetPages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
