<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:27.
 */
class ConcreteAssetLibraryHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteAssetLibraryHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/asset_library');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

	 public function testObjectCreated() {
		 $this->assertTrue($this->object instanceof ConcreteAssetLibraryHelper);
	}

    /**
     * @covers ConcreteAssetLibraryHelper::file
     * @todo   Implement testFile().
     */
    public function testFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAssetLibraryHelper::image
     * @todo   Implement testImage().
     */
    public function testImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAssetLibraryHelper::video
     * @todo   Implement testVideo().
     */
    public function testVideo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAssetLibraryHelper::text
     * @todo   Implement testText().
     */
    public function testText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAssetLibraryHelper::audio
     * @todo   Implement testAudio().
     */
    public function testAudio() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAssetLibraryHelper::doc
     * @todo   Implement testDoc().
     */
    public function testDoc() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAssetLibraryHelper::app
     * @todo   Implement testApp().
     */
    public function testApp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
