<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:27.
 */
class ConcreteAvatarHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteAvatarHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/avatar');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	public function testObjectCreated() {
		 $this->assertTrue($this->object instanceof ConcreteAvatarHelper);
	}
    /**
     * @covers ConcreteAvatarHelper::getStockAvatars
     * @todo   Implement testGetStockAvatars().
     */
    public function testGetStockAvatars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::outputUserAvatar
     * @todo   Implement testOutputUserAvatar().
     */
    public function testOutputUserAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::getImagePath
     * @todo   Implement testGetImagePath().
     */
    public function testGetImagePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::outputNoAvatar
     * @todo   Implement testOutputNoAvatar().
     */
    public function testOutputNoAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::processUploadedAvatar
     * @todo   Implement testProcessUploadedAvatar().
     */
    public function testProcessUploadedAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::removeAvatar
     * @todo   Implement testRemoveAvatar().
     */
    public function testRemoveAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::updateUserAvatar
     * @todo   Implement testUpdateUserAvatar().
     */
    public function testUpdateUserAvatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::updateUserAvatarWithStock
     * @todo   Implement testUpdateUserAvatarWithStock().
     */
    public function testUpdateUserAvatarWithStock() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteAvatarHelper::get_gravatar
     * @todo   Implement testGet_gravatar().
     */
    public function testGet_gravatar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
