<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:28.
 */
class ConcreteUrlsHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteUrlsHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/urls');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	 public function testObjectClass() {
		 $this->assertTrue($this->object instanceof ConcreteUrlsHelper);
	 }
    protected function tearDown() {
        
    }

    /**
     * @covers ConcreteUrlsHelper::getPackageIconURL
     * @todo   Implement testGetPackageIconURL().
     */
    public function testGetPackageIconURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUrlsHelper::getPackageURL
     * @todo   Implement testGetPackageURL().
     */
    public function testGetPackageURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUrlsHelper::getToolsURL
     * @todo   Implement testGetToolsURL().
     */
    public function testGetToolsURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUrlsHelper::getBlockTypeIconURL
     * @todo   Implement testGetBlockTypeIconURL().
     */
    public function testGetBlockTypeIconURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUrlsHelper::getBlockTypeAssetsURL
     * @todo   Implement testGetBlockTypeAssetsURL().
     */
    public function testGetBlockTypeAssetsURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUrlsHelper::getBlockTypeJavaScriptURL
     * @todo   Implement testGetBlockTypeJavaScriptURL().
     */
    public function testGetBlockTypeJavaScriptURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUrlsHelper::getBlockTypeToolsURL
     * @todo   Implement testGetBlockTypeToolsURL().
     */
    public function testGetBlockTypeToolsURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
