<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:28.
 */
class ConcreteInterfaceHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteInterfaceHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/interface');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	 public function testObjectClass() {
		 $this->assertTrue($this->object instanceof ConcreteInterfaceHelper);
	 }
    /**
     * @covers ConcreteInterfaceHelper::submit
     * @todo   Implement testSubmit().
     */
    public function testSubmit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::button
     * @todo   Implement testButton().
     */
    public function testButton() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::button_js
     * @todo   Implement testButton_js().
     */
    public function testButton_js() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::buttons
     * @todo   Implement testButtons().
     */
    public function testButtons() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::getQuickNavigationLinkHTML
     * @todo   Implement testGetQuickNavigationLinkHTML().
     */
    public function testGetQuickNavigationLinkHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::showWhiteLabelMessage
     * @todo   Implement testShowWhiteLabelMessage().
     */
    public function testShowWhiteLabelMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::getToolbarLogoSRC
     * @todo   Implement testGetToolbarLogoSRC().
     */
    public function testGetToolbarLogoSRC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::showNewsflowOverlay
     * @todo   Implement testShowNewsflowOverlay().
     */
    public function testShowNewsflowOverlay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::clearInterfaceItemsCache
     * @todo   Implement testClearInterfaceItemsCache().
     */
    public function testClearInterfaceItemsCache() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::cacheInterfaceItems
     * @todo   Implement testCacheInterfaceItems().
     */
    public function testCacheInterfaceItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteInterfaceHelper::tabs
     * @todo   Implement testTabs().
     */
    public function testTabs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
