<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:27.
 */
class ConcreteDashboardHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteDashboardHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/dashboard');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
	 public function testClasses() {
		 $this->assertTrue($this->object instanceof ConcreteDashboardHelper);
		 $this->assertTrue(class_exists('ConcreteDashboardMenu'));
		 $this->assertTrue(class_exists('ConcreteDashboardDefaultMenu'));
	 }


    /**
     * @covers ConcreteDashboardHelper::canRead
     * @todo   Implement testCanRead().
     */
    public function testCanRead() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::canAccessComposer
     * @todo   Implement testCanAccessComposer().
     */
    public function testCanAccessComposer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::inDashboard
     * @todo   Implement testInDashboard().
     */
    public function testInDashboard() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::getDashboardPaneFooterWrapper
     * @todo   Implement testGetDashboardPaneFooterWrapper().
     */
    public function testGetDashboardPaneFooterWrapper() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::getDashboardPaneHeaderWrapper
     * @todo   Implement testGetDashboardPaneHeaderWrapper().
     */
    public function testGetDashboardPaneHeaderWrapper() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::getDashboardPaneHeader
     * @todo   Implement testGetDashboardPaneHeader().
     */
    public function testGetDashboardPaneHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::getDashboardBackgroundImage
     * @todo   Implement testGetDashboardBackgroundImage().
     */
    public function testGetDashboardBackgroundImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::addQuickNavToMenus
     * @todo   Implement testAddQuickNavToMenus().
     */
    public function testAddQuickNavToMenus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteDashboardHelper::getDashboardAndSearchMenus
     * @todo   Implement testGetDashboardAndSearchMenus().
     */
    public function testGetDashboardAndSearchMenus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
