<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:27.
 */
class ConcreteScrapbookHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteScrapbookHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Loader::helper('concrete/scrapbook');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	 public function testObjectClass() {
		 $this->assertTrue($this->object instanceof ConcreteScrapbookHelper);
	 }
    /**
     * @covers ConcreteScrapbookHelper::getPersonalScrapbookName
     * @todo   Implement testGetPersonalScrapbookName().
     */
    public function testGetPersonalScrapbookName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteScrapbookHelper::getGlobalScrapbookPage
     * @todo   Implement testGetGlobalScrapbookPage().
     */
    public function testGetGlobalScrapbookPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteScrapbookHelper::getAvailableScrapbooks
     * @todo   Implement testGetAvailableScrapbooks().
     */
    public function testGetAvailableScrapbooks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteScrapbookHelper::getDefault
     * @todo   Implement testGetDefault().
     */
    public function testGetDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteScrapbookHelper::setDefault
     * @todo   Implement testSetDefault().
     */
    public function testSetDefault() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
