<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-11 at 17:48:27.
 */
class ConcreteFileHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteFileHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
		$this->object = Loader::helper('concrete/file');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

	/**
	 * Verifies that the loader returned the correct object
	*/
	public function testObjectCreated() {
		$this->assertInstanceOf('ConcreteFileHelper', $this->object);
	}

    /**
     * @covers ConcreteFileHelper::getSystemPath
     * @todo   Implement testGetSystemPath().
     */
    public function testGetSystemPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::getThumbnailSystemPath
     * @todo   Implement testGetThumbnailSystemPath().
     */
    public function testGetThumbnailSystemPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::getRelativePath
     * @todo   Implement testGetRelativePath().
     */
    public function testGetRelativePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::getFileRelativePath
     * @todo   Implement testGetFileRelativePath().
     */
    public function testGetFileRelativePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::getThumbnailRelativePath
     * @todo   Implement testGetThumbnailRelativePath().
     */
    public function testGetThumbnailRelativePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::mapSystemPath
     * @todo   Implement testMapSystemPath().
     */
    public function testMapSystemPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::getIncomingDirectoryContents
     * @todo   Implement testGetIncomingDirectoryContents().
     */
    public function testGetIncomingDirectoryContents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::serializeUploadFileExtensions
     * @todo   Implement testSerializeUploadFileExtensions().
     */
    public function testSerializeUploadFileExtensions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::unSerializeUploadFileExtensions
     * @todo   Implement testUnSerializeUploadFileExtensions().
     */
    public function testUnSerializeUploadFileExtensions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteFileHelper::getAllowedFileExtensions
     * @todo   Implement testGetAllowedFileExtensions().
     */
    public function testGetAllowedFileExtensions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
