name: Check Syntax

on:
  pull_request:
  push:

jobs:
  check-syntax:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # This list should include at least the value of Concrete\Core\Install\Preconditions\PhpVersion::MINIMUM_PHP_VERSION
          -
            php-version: "7.3"
            exclude: |
              tests/assets/Foundation/jobs/index_search.php
          -
            php-version: "8.5"
            exclude: |
              tests/assets/Foundation/jobs/index_search.php
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          exclude: ${{ matrix.exclude }}
          include: |
            concrete/bin/concrete
            concrete/bin/concrete5
          fail-on-warnings: true
