#!/usb/bin/php
<?php
define('DIR_BASE', __DIR__);
$DIR_BASE_CORE = __DIR__.'/concrete';

require $DIR_BASE_CORE . '/bootstrap/configure.php';
require $DIR_BASE_CORE . '/bootstrap/autoload.php';
$cms = require $DIR_BASE_CORE . '/bootstrap/start.php';

/* @var $cms \Concrete\Core\Application\Application */
if (!$cms->isRunThroughCommandLineInterface()) {
    return;
}
$app = new \Concrete\Core\Console\Application($cms);
$app->run();
